### ISSUE TITLE
Tab title unreadable

### ISSUE THREAD

**Issue by kai-oswald** [kai-oswald/NightOwl-VS-Theme#17]
In "Find and Replace" (ctrl + shift + f)
![image](https://user-images.githubusercontent.com/10707779/86209735-7f52fe00-bb73-11ea-9e47-aa4a6ce6aaad.png)

With mouseover:
![image](https://user-images.githubusercontent.com/10707779/86209764-8e39b080-bb73-11ea-93e7-94a28e67e0e9.png)

**Comment by DrThrillhouse** [comment]
Shortly, I'm going to make a PR as a suggestion to fix this issue and have the colors more in keeping with the rest of the theme. There are some trade-offs in the color selection I've gone with, because each item in the VSSearch palette can be used for multiple things in different parts of the search UI. I think I've achieved a decent compromise while sticking to the theme color scheme. One thing I couldn't fix: on this panel, I think it makes sense for the textbox borders to be visible, but unfortunately the VSSearch palette appears to inherit from CommonControls, so we couldn't achieve that without putting borders on all the other text boxes too.

![image](https://user-images.githubusercontent.com/14172590/88179611-c443ef00-cc5e-11ea-86aa-78dff8ad36f0.png)
![image](https://user-images.githubusercontent.com/14172590/88179670-d6be2880-cc5e-11ea-9536-c155ddc04b2a.png)
![image](https://user-images.githubusercontent.com/14172590/88179738-ea698f00-cc5e-11ea-9f8a-ce279246879c.png)

**Comment by kai-oswald** [comment]
Closed by #21
